version: "3.2"
services:
  app:
    build:
      dockerfile: ./Dockerfile  
    network_mode: host
    volumes:
      - ../.env/credentials.yml:/usr/project/credentials.yml
    command: python -m main